# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/sangitaGIT011/Myproj/blob/main/PDS_Sem1.ipynb
"""

#Practical 1

#b. Write and Execute Basic Python Programs Using Input/Output
#Basic
print ("Hello World in Python")

#Using user input
A=float (input("no1:"))
B=float (input ("no2:"))
sum=A+B
print("sum :",sum)


#c. Demonstrate Variable Declaration, Indentation, and Comments
stu_name='Rohan'
stu_age=21
stu_mark=91

print ("student Name:",stu_name)
print("student_age:",stu_age)
print ("student Mark:",stu_mark)

if stu_mark >= 90: #Classify grade based on mark
    print("Obtain Grade A++")
else:
    print("Obtain Grade  A+")

#Practical 2
# Operators and Expressions:
 #a. Use arithmetic, comparison, and logical operators.
 #b. Perform string concatenation and type conversion.
 #2c. Evaluate mathematical expressions using precedence rules
# Use arithmetic, comparison, and logical operators.
# arithmetic operator
print("***Arithmetic operator***")
a=float(input( "1st number:"))
b=float(input( "2nd number:"))


print("Addition of Number:",a+b)
print("Subtraction of Number:",a-b)
print("Multiplication of Number:",a*b)
print("Division of Number:",a/b)

#Comparison operator
print("***Comparison operator***")
print("1st number is greater than 2nd number:",a>b)
print("1st number is equal to 2nd number:",a==b)
print("1st number is not equal to 2nd number",a!=b)

#logical operator
a=True
b=False
print("***logical operator***")
print("a and b:",a and b)
print("a or b:",a or b)
print("a not b:", not b)

#Perform string concatenation and type conversion
# String Concatenation
print("***String Concatenation***")
first_str = "python"
last_str = "programming"
full_str = first_str + " " + last_str
print("Full Name:", full_str)

# Type Conversion
print("***Type Conversion***")

num_str = "10"
num_int = int(num_str)  # Convert string to integer
sum_result = num_int + 25
print("Sum after type conversion:", sum_result)

#c. Evaluate mathematical expressions using precedence rules
# Operator Precedence Example
print("***Evaluate mathematical expressions***")
result = 12 + 6 * 2 ** 3 / 4 - 6
# According to precedence: Exponentiation > Multiplication/Division > Addition/Subtraction
print("Result of expression :", result)

#Practicle 3
#Basic Problem-Solving Programs:
# a. Find maximum of three numbers.
# b. Calculate area and perimeter of simple shapes.
# c. Print sum of numbers within a given range.

print("***maximum numbers***")
a=float(input("1st number:"))
b=float(input("2nd number:"))
c=float(input("3rd number:"))

if a>b and b>c:
    print("Maximum number is:",a)

elif b>a and b>c:
    print("Maximum number is:",b)
else:
    print("Maximum number is:",c)

    # Program to calculate area and perimeter of a rectangle
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

area = length * width
perimeter = 2 * (length + width)


print("Area :", area)
print("Perimeter :", perimeter)

#sum of numbers within a given range.
num=int(input("Enter the first number:"))
number=int(input("Enter the second number:"))

sum=0
for i in range(num,number+1):
    sum+=i
print("sum of numbers within a given range:",sum)

#Practicle 4
#Conditional Statements:
 #a. Check if a number is positive, negative, or zero.
 #b. Determine if a given year is a leap year.
 #c. Classify student grades based on marks
print("*** check positive,negative or Zero***")
num=int(input("Enter number:"))
if num>0:
    print ("Positive number")
elif num<0:
    print("Negative number")
else:
    print("Zero")

print("**Leap Year***")

year=int(input("enter year:"))

if(year%400==0) or (year%100!=0 and year%4==0):
    print(year,"Leap Year")
else:
    print(year,"Not Leap Year")



mark=int(input("Enter mark:"))



if mark >= 90: #Classify grade based on mark
    grade="A+"
elif mark >= 80: #Classify grade based on mark
    grade="A"
elif mark>= 70: #Classify grade based on mark
    grade="B+"
elif mark>= 60: #Classify grade based on mark
    grade="B"
elif mark>= 50: #Classify grade based on mark
    grade="C"
elif mark>= 40: #Classify grade based on mark
    grade="D"
else:
    print("Fail")

print("Your grade is:", grade)

#Practicle 5
#Looping and Iteration:
 #a. Print all prime numbers within a given range.
 #b. Generate multiplication tables.
 #c. Demonstrate use of break, continue, and else in loops

print("*** prime numbers within a given range***")
s=int(input("Enter start number:"))
e=int(input("Enter end number:"))

print("Prime numbers between", s, "and", e ,"are:")

for num in range(s, e + 1):
    if num > 1:  # Prime numbers are greater than 1
        for i in range(2, int(num ** 0.5) + 1):
            if num % i == 0:
                break
        else:
            print(num)

print("***multiplication tables***")
num=int(input("enter number:"))

print("Multiplication table of:",num)
for num in range(1,11):
    print(num,"x",i,"=",num*i)

print("***Demo of Break,Continue,Loop***")

for num in range(1, 10):
    if num == 5:
        print("Skipping number 5 using continue.")
        continue
    if num == 8:
        print("Breaking the loop at number 8.")
        break
    print("Number:", num)
else:
    print("Loop completed without break.")

#Practicle 6
 #Introduction to Data Handling using Python:
 #a. Load sample dataset using pandas.
 #b. Display dataset info, column names, and shape.
 #c. Perform basic descriptive statistics

import pandas as pd
import seaborn as sns
data=sns.load_dataset('titanic')
 #a. Load sample dataset using pandas.
#print(data)

#print ("data loaded")
print(data.head())

#b. Display dataset info, column names, and shape.
data.info()
print(data.columns.tolist())
print(data.shape)


#c. Perform basic descriptive statistics
print(data.describe())

print(data.isnull().sum())

#Practicle 7
#Data Cleaning and Preparation:
# a. Handle missing values and duplicates.
# b. Convert data types and normalize numerical columns.
# c. Rename and reorder dataset columns.

import pandas as pd
import seaborn as sns

data=sns.load_dataset('titanic')

# a. Handle missing values and duplicates.
##  Fill missing values

data['age']=data['age'].fillna(data['age'].median())
data['embarked']=data['embarked'].fillna(data['embarked'].mode()[0])

if 'Nspec' not in data['deck'].cat.categories:
  data['deck'] = data['deck'].cat.add_categories(['Nspec'])
data['deck'] = data['deck'].fillna('Nspec')

# b. Convert data types and normalize numerical columns.

# Convert 'Age' to integer (if it’s float after filling NaN)
data['age'] = data['age'].astype(int)

# Normalize  'fare'
data['fare_normalized'] = (data['fare'] - data['fare'].min()) / (data['fare'].max() - data['fare'].min())



#print("\n--- Normalized Columns Preview ---")
print(data[['fare', 'fare_normalized']].head())


# c. Rename and reorder dataset columns.
# Rename selected columns for clarity
data.rename(columns={'sex': 'gender', 'embarked': 'embark_location','alive':'Alive','alone':'Alone'}, inplace=True)

#print(data.columns.tolist())

print(data.head())
## Apply new order (only include columns that exist)

## Move selected columns to front
cols_to_front = ['age']
new_columns = cols_to_front + [col for col in data.columns if col not in cols_to_front]
data = data[new_columns]

print(data.columns.tolist())

#Practicle 8
#Data Transformation and Feature Engineering:
 #a. Apply filtering and conditional selection on DataFrame.
 #b. Use apply() and lambda to modify columns.
 #c. Create new derived columns.

 #a. Apply filtering and conditional selection on DataFrame.
import pandas as pd
import seaborn as sns

# Load the Titanic dataset
data = sns.load_dataset('titanic')

## Display first few rows


#print(data.head())

print ('***passengers older than 50***')
older_passengers = data[data['age'] > 50]
print("\nPassengers older than 50:\n", older_passengers[['age', 'sex', 'survived']].head())


 #b. Use apply() and lambda to modify columns.

data['age_group'] = data['age'].apply(lambda x:
                                      'Child' if x < 18 else
                                      'Adult' if x < 60 else
                                      'Senior')
print("\nAdded age_group column:\n", data[['age', 'age_group']].head(10))

 #c. Create new derived columns.
data['family_size'] = data['sibsp'] + data['parch'] + 1
data['fare_per_person'] = data['fare'] / data['family_size']

print("\nNew derived columns (family_size, fare_per_person):\n",
      data[['fare', 'family_size', 'fare_per_person']].head())

#Practicle 9
#Data Visualization and EDA:
 #a. Plot histograms, bar charts, and line charts using matplotlib.
 #b. Visualize relationships with scatterplots and boxplots.
 #c. Generate correlation heatmaps and draw insights.


import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = sns.load_dataset('mpg')

print("\n--- Dataset Preview ---")
print(data.head())
print("\n--- Basic Info ---")
print(data.info())
print("\n--- Summary Statistics ---")
print(data.describe())

print("Histogram")
plt.figure(figsize=(6,4))
plt.hist(data['mpg'].dropna(), bins=20, color='lightgreen', edgecolor='black')
plt.title('Distribution of Miles Per Gallon (MPG)')
plt.xlabel('MPG')
plt.ylabel('Frequency')
plt.show()

print("Bar Chart")
plt.figure(figsize=(6,4))
data.groupby('origin')['mpg'].mean().plot(kind='bar', color=['skyblue', 'salmon', 'lightgreen'])
plt.title('Average MPG by Origin')
plt.xlabel('Origin')
plt.ylabel('Average MPG')
plt.show()

print("Line Chart")
plt.figure(figsize=(6,4))
data.groupby('model_year')['mpg'].mean().plot(kind='line', marker='o', color='orange')
plt.title('Average MPG by Model Year')
plt.xlabel('Model Year')
plt.ylabel('Average MPG')
plt.grid(True)
plt.show()


 #b. Visualize relationships with scatterplots and boxplots.
print(" Relationships with scatterplots and boxplots.")

print('scatterplots')
plt.figure(figsize=(6,4))
sns.scatterplot(x='horsepower', y='mpg', hue='origin', data=data)
plt.title('Horsepower vs MPG by Origin')
plt.show()

print('Boxplots')
plt.figure(figsize=(6,4))
sns.boxplot(x='cylinders', y='mpg', data=data, color='skyblue')
plt.title('MPG Distribution by Cylinder Count')
plt.show()


print('correlation')

corr = data.select_dtypes(include='number').corr()

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap='viridis', fmt='.2f')
plt.title('Correlation Heatmap of Vehicle Features')
plt.show()

#Practicle 10
 #Working with Lists and Tuples:
 #a. Create and modify lists using slicing and indexing.
 #b. Perform list methods: append, insert, sort, pop.
 #c. Demonstrate tuple immutability and unpacking.

  #a. Create and modify lists using slicing and indexing.
print("Create using slicing and indexing.")
vegtables=['Potato','Tomato','Cabbage','Chilli']
print(vegtables)
print('**using Indexing**')
print(vegtables[0])
print(vegtables[3])


print('**using slicing**')
print(vegtables[::1])
print(vegtables[::2])
print(vegtables[1::])


print('**modify List**')
vegtables[3]='Onion'
print(vegtables)

print('**modify Slicet**')
vegtables[2:4]=['Garlic','Ginger']
print(vegtables)



# b.Perform list methods: append, insert, sort, pop.


# Append adds an element at the end
vegtables.append("Chilli")
print("After append:", vegtables)

# Insert adds at a specific index
vegtables.insert(2, "Cabbage")
print("After insert:", vegtables)

# Sort the list alphabetically
vegtables.sort()
print("After sorting:", vegtables)

# Pop removes the last element (or by index)
removed_item = vegtables.pop()
print("After pop:", vegtables)
print("Removed item:", removed_item)


#c. Demonstrate tuple immutability and unpacking.


# Create a tuple
colors = ("red", "green", "blue")
print("\nTuple:", colors)

# Access elements
print("First color:", colors[0])


# Tuple Unpacking
(r, g, b) = colors
print("Unpacked values:")
print("r =", r)
print("g =", g)
print("b =", b)

# Nested tuple unpacking
person = ("Alice", 25, ("New York", "USA"))
(name, age, (city, country)) = person
print("\nTuple Unpacking Example:")
print(f"Name: {name}, Age: {age}, City: {city}, Country: {country}")

#Practicle 11
#Working with Sets and Dictionaries:
 #a. Perform set operations: union, intersection, difference.
 #b. Add, update, and delete dictionary items.
 #c. Iterate through key-value pairs and check membership.


#a. Perform set operations: union, intersection, difference.

# Create two sets
set_a = {1, 2, 3, 4, 5}
set_b = {4, 5, 6, 7, 8}

print("Set A:", set_a)
print("Set B:", set_b)

# Union – elements from both sets
print("\nUnion:", set_a.union(set_b))

# Intersection – common elements
print("Intersection:", set_a.intersection(set_b))

# Difference – elements in A not in B
print("Difference (A - B):", set_a.difference(set_b))

# Symmetric Difference – elements in either A or B, but not both
print("Symmetric Difference:", set_a.symmetric_difference(set_b))

# Membership Test
print("Is 3 in set A?", 3 in set_a)
print("Is 7 not in set A?", 7 not in set_a)

 #b. Add, update, and delete dictionary items.
#Create a dictionary
student = {
    "name": "Rohan",
    "age": 21,
    "course": "post graduation diploma in data science "
}
print("\nOriginal Dictionary:", student)

# Add new item
student["grade"] = "A"
print("After adding grade:", student)

# Update existing item
student["age"] = 22
print("After updating age:", student)

# Delete a specific key-value pair
del student["course"]
print("After deleting course:", student)

# Remove an item using pop()
removed = student.pop("grade")
print("Removed item:", removed)
print("After pop:", student)


#c. Iterate through key-value pairs and check membership.

# Rebuild dictionary
student = {"name": "Vishnu", "age": 23, "grade": "B"}

# Iterate through keys and values
print("\nIterating through dictionary:")
for key, value in student.items():
    print(f"{key}: {value}")

# Check membership
print("\nIs 'name' a key in student?", 'name' in student)
print("Is 'course' not a key in student?", 'course' not in student)

# Access keys and values separately
print("\nAll keys:", list(student.keys()))
print("All values:", list(student.values()))

#Practicle 12
#String Manipulation and Formatting:
 #a. Perform slicing and case conversion operations.
 #b. Count vowels, digits, and words.
 #c. Use string functions: split(), replace(), join(), find()

 #a. Perform slicing and case conversion operations.

text = "Python Programming Language"

print("Original String:", text)

# Slicing
print("\nSlicing Examples:")
print("First 6 characters:", text[:6])
print("Last 8 characters:", text[-8:])
print("Characters 7 to 17:", text[7:18])

# Case Conversion
print("\nCase Conversions:")
print("Uppercase:", text.upper())
print("Lowercase:", text.lower())
print("Title Case:", text.title())
print("Swap Case:", text.swapcase())
print("Capitalize:", text.capitalize())


 #b. Count vowels, digits, and words.

sample = "Python 3 is fun and powerful!"

vowels = "aeiouAEIOU"
vowel_count = sum(1 for ch in sample if ch in vowels)
digit_count = sum(1 for ch in sample if ch.isdigit())
word_count = len(sample.split())

print("\nSample String:", sample)
print("Vowels:", vowel_count)
print("Digits:", digit_count)
print("Words:", word_count)


 #c. Use string functions: split(), replace(), join(), find()

sentence = "Data Science is the future of technology"

# split() → converts string into list
words = sentence.split()
print("\nWords List:", words)

# replace() → replaces part of the string
new_sentence = sentence.replace("future", "heart")
print("After Replace:", new_sentence)

# join() → joins list elements into string
joined_sentence = "-".join(words)
print("After Join with '-':", joined_sentence)

# find() → finds the position of substring
pos = sentence.find("Science")
print("Position of 'Science':", pos)

# Example of formatted string (f-string)
name = "Richard"
marks = 95
print(f"\nFormatted String Example: {name} scored {marks}% in Python test.")

#Practicle 13
 #Advanced Data Structure Applications:
 #a. Use nested lists and dictionaries for data storage.
 #b. Compare two lists for same elements (unordered).
 #c. Merge and sort dictionary data by key and value.

 # ==========================================
# Import required libraries
# ==========================================
import pandas as pd
import seaborn as sns

# Load a unique dataset
data = sns.load_dataset('penguins')
print(" Dataset Loaded Successfully!\n")
#print(data.head())

#a. Use nested lists and dictionaries for data storage.

# Select a few columns for structured data representation
subset = data[['species', 'island', 'bill_length_mm', 'bill_depth_mm']].dropna().head(5)

#  Option 1: Use unique keys (species + index)
nested_dict = {f"{row['species']}_{i}": {
                    'island': row['island'],
                    'bill_length_mm': row['bill_length_mm'],
                    'bill_depth_mm': row['bill_depth_mm']
                }
               for i, row in subset.head(5).iterrows()}

print("Nested Dictionary Example (Fixed):")
for key, value in nested_dict.items():
    print(f"{key} → {value}")

    # Get species present on two islands
island_1 = data[data['island'] == 'Torgersen']['species'].dropna().unique().tolist()
island_2 = data[data['island'] == 'Dream']['species'].dropna().unique().tolist()

print("\nSpecies on Torgersen Island:", island_1)
print("Species on Dream Island:", island_2)

 #b. Compare two lists for same elements (unordered).
same_species = set(island_1) == set(island_2)
print("\nDo both islands have same species?", same_species)

# Create summary dictionaries
avg_bill_length = data.groupby('species')['bill_length_mm'].mean().round(2).to_dict()
avg_bill_depth  = data.groupby('species')['bill_depth_mm'].mean().round(2).to_dict()

print("\nAverage Bill Length per Species:", avg_bill_length)
print("Average Bill Depth per Species:", avg_bill_depth)

 #c. Merge and sort dictionary data by key and value.
merged = {sp: {'bill_length': avg_bill_length[sp], 'bill_depth': avg_bill_depth[sp]}
          for sp in avg_bill_length}

print("\n Merged Dictionary:")
for species, stats in merged.items():
    print(f"{species}: {stats}")

# Sort dictionary by species name (key)
sorted_by_key = dict(sorted(merged.items()))
print("\nSorted by Key (Species Name):", sorted_by_key)

# Sort dictionary by bill length (value)
sorted_by_length = dict(sorted(merged.items(), key=lambda x: x[1]['bill_length']))
print("\nSorted by Bill Length (Ascending):", sorted_by_length)

#Practile 14
#Loop Applications and Recursion:
 #a. Calculate factorial of a number.
 #b. Generate Fibonacci series using recursion.
 #c. Compute GCD and LCM using recursion.

  #a. Calculate factorial of a number.
print('*Calculate factorial of a number*')
print('\n')

num=int(input('Enter a number: '))
def factorial(n):
    """Return factorial of n using recursion."""

    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(f"Factorial of {num} is: {factorial(num)}")


# b. Fibonacci series
print('\n')
print('Fibonacci Series')
num=int(input('Enter a number: '))
terms = int(input('Enter a terms: '))
def fibonacci(n):
    """Return nth Fibonacci number using recursion."""
    if n <= 1:
        return n
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)


print(f"\nFirst {terms} Fibonacci numbers:")
for i in range(terms):
    print(fibonacci(i), end=" ")
print()
 #c. GCD and LCM using recursion.
print('\n')
print('GCM AND LCM')
x=int(input('Enter a number: '))
y=int(input('Enter a number: '))

def gcd(a, b):
    """Return GCD using Euclidean recursion."""
    if b == 0:
        return a
    else:
        return gcd(b, a % b)

def lcm(a, b):
    """Return LCM using GCD."""
    return abs(a * b) // gcd(a, b)

#x, y = 24, 36
print(f"\nGCD of {x} and {y} is: {gcd(x, y)}")
print(f"LCM of {x} and {y} is: {lcm(x, y)}")

#Practicle 15

 #Pattern Generation and Conditional Loops:
 #a. Display number and star patterns using nested loops.
 #b. Print Pascal’s triangle.
 #c. Print all Armstrong and perfect numbers in a range

 #a. Display number and star patterns using nested loops.
print('Display number and star patterns')
num=int(input('Enter a number: '))
rows=int(input('Enter a row: '))
#rows = 7

print("Number Pattern:")
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

print("\nStar Pyramid Pattern:")
for i in range(1, rows + 1):
    print("*" * i)

print("\nReverse Star Pattern:")
for i in range(rows, 0, -1):
    print("*" * i)

 #b. Print Pascal’s triangle.
def factorial(n):
    if n == 0 or n == 1:
        return 1
    return n * factorial(n - 1)

def pascal_triangle(n):
    for i in range(n):
        for j in range(n - i + 1):
            print(" ", end="")  # spacing
        for k in range(i + 1):
            print(factorial(i) // (factorial(k) * factorial(i - k)), end=" ")
        print()

print("\nPascal’s Triangle:")
pascal_triangle(6)

 #c. Print all Armstrong and perfect numbers in a range
def is_armstrong(num):
    power = len(str(num))
    total = sum(int(digit) ** power for digit in str(num))
    return total == num

# Perfect number → sum of divisors (excluding num) == num
def is_perfect(num):
    if num < 2:
        return False
    divisors_sum = sum(i for i in range(1, num) if num % i == 0)
    return divisors_sum == num

start, end = 1, 1000
armstrong_nums = [n for n in range(start, end + 1) if is_armstrong(n)]
perfect_nums = [n for n in range(start, end + 1) if is_perfect(n)]

print(f"\nArmstrong Numbers between {start} and {end}:")
print(armstrong_nums)

print(f"\nPerfect Numbers between {start} and {end}:")
print(perfect_nums)

#Practicle 16
#User Interaction Programs:
 #a. Read student details (Name, Marks) and compute total/percentage.
 #b. Determine senior citizen eligibility.
 #c. Compute sum of comma-separated numbers entered by user.

# Program: Read student details and compute total and percentage

# Create an empty list to store student data
students = []

# Input number of students
n = int(input("Enter number of students: "))

for i in range(n):
    print(f"\nEnter details for Student {i+1}:")
    name = input("Enter student name: ")

    # Input marks separated by commas
    marks_input = input("Enter marks separated by commas (e.g., 85,90,78): ")

    # Convert string input into a list of integers
    marks = [int(x.strip()) for x in marks_input.split(",")]

    # Calculate total and percentage
    total = sum(marks)
    percentage = total / len(marks)

    # Store student record in a dictionary
    student = {
        "Name": name,
        "Marks": marks,
        "Total": total,
        "Percentage": percentage
    }
    students.append(student)

# Display results
print("\n📊 Student Results")
print("-" * 45)
print(f"{'Name':<15}{'Total':<10}{'Percentage':<10}")
print("-" * 45)

for s in students:
    print(f"{s['Name']:<15}{s['Total']:<10}{s['Percentage']:.2f}%")

# Program to determine senior citizen eligibility

# Take age input from user
age = int(input("Enter your age: "))

# Check eligibility
if age >= 60:
    print("You are a Senior Citizen. Eligible for senior citizen benefits.")
else:
    print("You are not a Senior Citizen yet.")

    # Program to compute the sum of comma-separated numbers

# Take input from the user
numbers_input = input("Enter numbers separated by commas: ")

# Convert input string into a list of numbers
numbers = [float(x.strip()) for x in numbers_input.split(",")]

# Calculate sum
total_sum = sum(numbers)

# Display result
print(f"\nNumbers entered: {numbers}")
print(f"Total Sum = {total_sum}")

#Practicle 17
#Functions and Arguments:
 #a. Define functions with positional, keyword, and default arguments.
 #b. Return multiple values from a function.
 #c. Use lambda functions with map(), filter(), reduce().



# a. Functions with positional, keyword, and default arguments


def student_info(name, course, age=18):  # 'age' is a default argument
    print(f"Name: {name}")
    print(f"Course: {course}")
    print(f"Age: {age}")

# Positional arguments
student_info("Rahul", "B.Sc")

# Keyword arguments
student_info(course="B.Com", name="Sneha", age=21)

# Mix of positional and default
student_info("Anjali", "B.A")

print("\n------------------------------")


# b. Function returning multiple values


def calculate_marks(m1, m2, m3):
    total = m1 + m2 + m3
    average = total / 3
    grade = "A" if average >= 75 else "B" if average >= 60 else "C"
    return total, average, grade  # returning multiple values

# Unpacking multiple return values
total, average, grade = calculate_marks(80, 70, 90)
print(f"Total: {total}, Average: {average:.2f}, Grade: {grade}")

print("\n------------------------------")


# c. Lambda functions with map(), filter(), and reduce()


# Import reduce
from functools import reduce

numbers = [2, 5, 8, 10, 3, 6]

# map() → apply a function to all elements
squared = list(map(lambda x: x ** 2, numbers))
print("Squared Numbers:", squared)

# filter() → filter elements based on a condition
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print("Even Numbers:", even_numbers)

# reduce() → accumulate results (sum in this case)
sum_all = reduce(lambda a, b: a + b, numbers)
print("Sum of All Numbers:", sum_all)

#Practicle 18
#Scope and Recursion Concepts:
 #a. Demonstrate local, global, and nonlocal variables.
 #b. Use nested functions and variable scope.
 #c. Reverse string using recursion.


# a. Demonstrate local, global, and nonlocal variables


x = "Global Variable"  # Global variable

def outer_function():
    x = "Outer Variable"  # Enclosed (nonlocal) variable

    def inner_function():
        nonlocal x  # Refers to variable in outer_function
        x = "Modified by Inner Function"
        print("Inner Function:", x)

    inner_function()
    print("Outer Function:", x)

outer_function()
print("Global Scope:", x)

print("\n------------------------------")

# b. Use nested functions and variable scope

def calculator(a, b):
    def add():
        return a + b

    def multiply():
        return a * b

    def subtract():
        return a - b

    # Accessing inner functions (nested)
    print("Addition:", add())
    print("Multiplication:", multiply())
    print("Subtraction:", subtract())

calculator(10, 5)

print("\n------------------------------")


# c. Reverse string using recursion


def reverse_string(s):
    if len(s) == 0:
        return s
    else:
        return reverse_string(s[1:]) + s[0]

# Example
word = "Python"
print(f"Original String: {word}")
print(f"Reversed String: {reverse_string(word)}")

# mymodule.py
def greet(name):
    return f"Hello, {name}! Welcome to Python modules."

def square(num):
    return num * num